import type { Specialist } from "./types"

export const specialists: Specialist[] = [
  {
    id: "patricio",
    name: "Patricio",
    specialty: "Plomero",
    highlight: "Especialista Estrella",
    schedule: "Lunes a Viernes",
    hours: "5 am a 1pm",
    rating: 5,
    available: true,
    extraFee: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Os5ybuUbg3UouzmEtirxQyI9dOuMUE.png",
    category: "Plomeria",
    horario: "Matutino",
    pricePerVisit: 1500,
  },
  {
    id: "maria",
    name: "Maria",
    specialty: "Electricista",
    highlight: "10 anios de experiencia",
    schedule: "Lunes a Viernes",
    hours: "9 am a 3pm",
    rating: 4,
    available: true,
    extraFee: 0,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Os5ybuUbg3UouzmEtirxQyI9dOuMUE.png",
    category: "Electricidad",
    horario: "Matutino",
    pricePerVisit: 1200,
  },
  {
    id: "antonio",
    name: "Antonio",
    specialty: "Carpintero",
    highlight: "Maestro de madera",
    schedule: "Fines de semana",
    hours: "9am a 9pm",
    rating: 5,
    available: false,
    extraFee: 400,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-2chV9FqxHG23qwNSnrI0lga5f24twI.png",
    category: "Carpinteria",
    horario: "Completo",
    pricePerVisit: 3000,
  },
  {
    id: "jose",
    name: "Jose",
    specialty: "Mantenimiento de climas",
    highlight: "Nuevo ingreso",
    schedule: "Lunes a Jueves",
    hours: "2pm a 2am",
    rating: 1,
    available: false,
    extraFee: 100,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Os5ybuUbg3UouzmEtirxQyI9dOuMUE.png",
    category: "Mantenimiento",
    horario: "Vespertino",
    pricePerVisit: 2000,
  },
  {
    id: "jennifer",
    name: "Jennifer",
    specialty: "Cerrajera",
    highlight: "20 anios en el oficio",
    schedule: "Fines de semana",
    hours: "10 am a 10 pm",
    rating: 4,
    available: false,
    extraFee: 300,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-2chV9FqxHG23qwNSnrI0lga5f24twI.png",
    category: "Cerrajeria",
    horario: "Completo",
    pricePerVisit: 1000,
  },
]
